### ISSUE TITLE
wrap lines menu bug

### ISSUE THREAD

**Issue by mjbaldwin** [fileability/chocolat-public#1025]
I like to show the 80 col gray line, but *not* have the text actually wrap -- I just want to see what visual point I should use as a limit.

Well, it turns out I can actually do this if I choose `Chocolat > Preferences > Wrap Guideline > Ruled`, check `View > Wrap Lines`, select `View > Wrap > 80`, and then *uncheck* `View > Wrap Lines`. Woo-hoo!

However, the checkbox under `View > Wrap` changes to `Don't Wrap` instead of staying at `80`. Which is technically correct, but the interface (menu) no longer indicates the fact that I now have a line showing at column 80. It's like a secret invisible preference option!

So despite the fact that I have the functionality I want, it kind of feels like a bug that it works the way I want it to, because it doesn't correspond with the menu options. I would suggest changing the menu options from:

```
View > Wrap Lines
View > Wrap > Don't Wrap
View > Wrap > -
View > Wrap > Fit to Window
View > Wrap > -
View > Wrap > 40
View > Wrap > 78
View > Wrap > 80
```

(having "wrap lines" not checked and "don't wrap" checked is redundant)

to:

```
View > Wrap Lines
View > Show Line Limit
View > Line Limit > Fit to Window
View > Line Limit > -
View > Line Limit > 40
View > Line Limit > 78
View > Line Limit > 80
```

or something along those lines. This way it's clear that you can wrap and/or show the line limit.

**Comment by locks** [comment]
This should be addressed with the new "Margin Preferences…" window.
