### ISSUE TITLE
Korean text and ? character

### ISSUE THREAD

**Issue by jongampark** [fileability/chocolat-public#1061]
When I write in Korean text, overall it's very good.
However, one thing I noticed was that it displays "D" when I put "?" at the end of a sentence. Although pressing a space bar or return key put "?" correctly, it's kind of annoying to see "D" while typing.
Probably it's because it can't determine what keys are typed next, so it just display a character based on nearest matching intermediate code in Unicode.

I hope it would be solved.

BTW, I love the Chocolat! 
Thanks for the great editor!

**Comment by fileability** [comment]
Fixed this a while back. Closing
