### ISSUE TITLE
Jumping to files doesn’t maintain scroll position

### ISSUE THREAD

**Issue by jbrennan** [fileability/chocolat-public#1623]
1. Open a file, scroll to a certain place.
2. Open another file, make an edit.
3. Use Cmd+D to go back to your previous file.

Expected: You should be at the same insertion point / scroll location you were when you left the file.
Actual: Who knows! Usually you’re scrolled somewhere else.

Reproducible: Frequently enough to make Chocolat a pain to use regularly. This bug has been around forever.

**Comment by jcbsnd** [comment]
I experience this bug constantly (literally in every project), it's quite annoying. Though, I don't use Cmd+D to move between files, I just click the filename in the list Active files. I have to move the cursor one character to get the editor to scroll to the right position. I've tried to clear the Application Settings and make a complete re-install, but it didn't resolve the problem. How can I help you to nail this bug?

**Comment by jbrennan** [comment]
Yep, still a problem in the latest Chocolat on Yosemite. What can I provide to help fix this issue? It's starting to become a dealbreaker and I'd love to help fix it.

**Comment by j0hnn** [comment]
Still happening. It's not intermittent for me - happens every file switch in every project. I'm happy to give any and all info that will help you fix this sort-of showstopping bug.

**Comment by fileability** [comment]
One way to reproduce this is to open up two active files, then scroll to the bottom of one (making sure the  cursor isn't visible), then switch to file B, then switch back to file A.

I don't know why this happens though.

**Comment by j0hnn** [comment]
Still happening in 3.2.1

=/

**Comment by fileability** [comment]
Yes, I know :P

So I added some logging and as far as I can tell, Chocolat is not attempting to set the scroll position of active files. Which makes sense, because they stay open, so theoretically they shouldn't need it.

**Comment by fileability** [comment]
Basically the problem is that RBSplitView really doesn't like the way we use it, and so I will have to write my own split view.

**Comment by j0hnn** [comment]
I'm not familiar with Cocoa, but that doesn't sound fun.

But I'm **extremely** excited that you're at least looking at this again - thank you!. :)

**Comment by fileability** [comment]
Yeah it's very not fun, and I'm not sure whether it will fix it either. But it has to be done.

There are so many hax to make the current split view work, it's clouding out the code so I can't understand what's going on. On the plus side, this will solve some of the other split view problems that have been in chocolat forever.

**Comment by fileability** [comment]
Done! https://gist.github.com/fileability/3574f652b0a19272f77c

**Comment by fileability** [comment]
As far as I can tell, this is fixed! :grinning: If this issue is still a problem after 3.2.2 hits, please comment on this issue or open a new one.
