### ISSUE TITLE
Tabstops stay active

### ISSUE THREAD

**Issue by tobiastom** [fileability/chocolat-public#1693]
When I create a new snippet with multiple tabletops, like this:

```
%{1="public"} function %{2}(%{3}) {
	%{4}
}
```

I can access all tabstops with `TAB` – which is nice. When I enter multiple lines on tabstop `%{4}`, and try to indent some lines with `TAB`, the text I just entered will get selected and I cannot add some indentation to the line.

![tabstop](https://cloud.githubusercontent.com/assets/49210/5568746/f351d86e-8f62-11e4-8a45-1453a6106ad7.gif)

**Comment by fileability** [comment]
try this

    %{1="public"} function %{2}(%{3}) {
        %{0}
    }

**Comment by tobiastom** [comment]
Seems to work. Why? :)
