### ISSUE TITLE
Use Yosemite-style tabs

### ISSUE THREAD

**Issue by cjhowe** [fileability/chocolat-public#1700]
Yosemite has a new style for tabs. It would be cool if chocolat supported this.

![screenshot 2015-01-14 01 37 50]
 (https://cloud.githubusercontent.com/assets/9828236/5735079/325ec31e-9b8e-11e4-9796-5531898eb9e0.png)

**Comment by locks** [comment]
This change would be too expensive to implement, so it's not something likely to be done.
