### ISSUE TITLE
Chocolat asked to upgrade; now demands $15?

### ISSUE THREAD

**Issue by BoboFraggins** [fileability/chocolat-public#1705]
I was using Chocolat, it crashed, on launch it offered to upgrade, now it is locked out and demanding $15.

**Comment by fileability** [comment]
Everything we've ever shipped can be downloaded here: http://chocolatapp.com/release-blog

v3 does cost money. v2 doesn't really work on Yosemite very well, and will be rendered useless whenever Apple removes GC anyway.

If it wasn't for the $15 fee, I wouldn't have had the ability to make v3, which would have meant Chocolat was a dead man walking. I'm not really a capitalist, I would prefer to use shells or yams, but I can't change the world we live in.

**Comment by BoboFraggins** [comment]
I don't expect you to work for free. I bought the original version after all.

I was complaining about you offering to upgrade without any hint I was about to get locked out of the editor. There may very well be some way to go find an old version, but I didn't know that. All I saw was an offer to upgrade, and then a demand to pay more money to continue working. I have no intention of paying what amounts to a ransom. If you had put up an offer to pay for an upgrade, I would have paid.

As I had a deadline, I switched editors. You may want to consider that I might not be the only customer you'll lose from this.

**Comment by fileability** [comment]
I couldn't put in a message without pushing an update. And I couldn't push an update without putting in a message. Catch-22 situation really.

Losing customers is never fun, but losing the whole *product* means losing them all. The fact that Chocolat v3 exists and shipped on time means that Chocolat will live to fight another day.
