### ISSUE TITLE
Run and REPL actions not working for Ruby

### ISSUE THREAD

**Issue by endersstocker** [fileability/chocolat-public#1706]
When I select these options with a Ruby file open, nothing occurs. Terminal is not launched.

**Comment by locks** [comment]
Cannot reproduce, as actions work as expected. Can you provide your OS and Chocolat versions?
Are you using a Ruby version manager, if so which?
Thanks.

**Comment by endersstocker** [comment]
When I opened *.rb files, they were being recognized as Ruby on Rails, instead of plain old Ruby. So command+R did nothing. Now that I’ve switched the files to Ruby, all is well.
