### ISSUE TITLE
Missing Julia syntax highlighting

### ISSUE THREAD

**Issue by jcbsnd** [fileability/chocolat-public#1709]
It would be really nice to have syntax highlighting for [Julia](http://julialang.org) code.

**Comment by locks** [comment]
@jcbsnd could you try importing the (https://github.com/WestleyArgentum/Julia.tmbundle)[Julia.tmbundle]?

**Comment by jcbsnd** [comment]
It seems to be working alright. I'll report back if there are any problems. Thanks!

**Comment by locks** [comment]
Glad to help :)
