### ISSUE TITLE
Option "Enable cmd-cmd Documentation" does not persist

### ISSUE THREAD

**Issue by tsbehlman** [fileability/chocolat-public#1715]
Issue seen in version 3.1.4 on 10.9.5.  Disabling the option works as long as Chocolat stays open, but after quitting and relaunching Chocolat, the option is enabled again.

**Comment by fileability** [comment]
huh, that is strange

**Comment by tsbehlman** [comment]
Disabling the option correctly sets sets CHShowDoubleTapDocPopovers to false in the preference file (~/Library/Preferences/com.chocolatapp.Chocolat.plist) and this persists after quitting Chocolat.  After reopening, however, the option is flipped back to true.

**Comment by locks** [comment]
This has been fixed and will be in 3.2
