### ISSUE TITLE
Font name and size display as null.

### ISSUE THREAD

**Issue by ujvaljoshi** [fileability/chocolat-public#1735]
It doesn't cause any issues in editor but doesn't look right. It happens occasionally.

![null_bug](https://cloud.githubusercontent.com/assets/870044/8931252/645904c0-3552-11e5-8012-656ff4837126.png)

**Comment by ujvaljoshi** [comment]
Its on Chocolat 3.1.4 and OS version is 10.10.3

**Comment by fileability** [comment]
I don't think this is a bug. If the font you had was removed it will display as null then default to Menlo. Appears to be working correctly.

**Comment by ujvaljoshi** [comment]
I get it. Might be issue after I made clean install of El Capitan.
