### ISSUE TITLE
OS X State Preservation

### ISSUE THREAD

**Issue by borisyurkevich** [fileability/chocolat-public#1739]
OS X Lion introduced new API — [state preservation.](http://arstechnica.com/apple/2011/07/mac-os-x-10-7/7/#document-model) I think it is time for Chocolat to support it, especially if it wants to be a modern app.

1. Settings > General > Uncheck "Close windows when quoting an app"
2. Create new text file and save it
3. Drag it to the bottom left corner of the screen
4. Quit the app

**Expected:** everything as you left it.
**Actual:** Chocolat closed your file and created new one instead.

**Comment by locks** [comment]
I believe this is a duplicate.
