### ISSUE TITLE
Text Lines Sort Ascending sometimes yield wrong sort result

### ISSUE THREAD

**Issue by dougdin** [fileability/chocolat-public#1752]
Lines with numbers mixed in, do not always sort correctly.
When sorting the 6 example lines shown below using
Text -> Lines -> Sort Ascending ^S

The following is 6 example lines as I expected to see them after sorting:

john hash 111 code
john hash 22b code
john hash 2ab code
john hash 3af code 211
john hash 3af code 38c
john hash 3af code 4bb

But what I got from chocolat's sort was this:

john hash 2ab code
john hash 3af code 4bb
john hash 3af code 38c
john hash 3af code 211
john hash 22b code
john hash 111 code

This is NOT what I expected from an ascii sort.
Sublime and the command line sort return results as expected.

It seams to be treating the numbers separately from the string data and then sorting them numerically.  This might be useful for a numbered list.  But seems wrong for most other datasets where an ascii sort is expected and digits are present in the dataset.  I have found no settings so far to change the way a sort is done.

This clearly seems to be an bug to me.

another example set which sorts wrong
6fb7a
7e781
35d92
92daa
6787a

I expected
35d92
6787a
6fb7a
7e781
92daa

I am running chocolat version 3.1.7 
on OSX 10.11.2 ElCapitan

**Comment by fileability** [comment]
This is a feature, it uses localizedStandardCompare from Cocoa to sort numbers in the right order.

It wouldn't be hard to add a "dumb" sort, although I admit I never really anticipated anybody would need that.

**Comment by dougdin** [comment]
Thanks for the response.  Sorry, I see now this is not a bug but intended behaviour.  I just unexpected certain results when dealing with hex values, hashes and some filenames, where there may be sequences of digits, but they hold no numeric significance.

Clearly the finder style sorting can hold appeal otherwise. I guess I'm just so used to past editors doing a pure ascii style sort that it didn't occur to me that a different method had been employed.

For now I can use one of the other editors (or the commandline sort) when dealing with data containing digits that are just part of a sequence of bytes (i.e. sha and md5sums and filenames with hex strings in them).  

If you can add an option for a plain sort at some point that would be helpful when dealing with some datasets, but for now I will close this as it is not a bug.

**Comment by fileability** [comment]
Well... implementing it is trivial, the problem is where to put it. I don't want to overload Text -> Lines with lots of different kinds of sorts, and I can't hide it behind a modifier without taking up 3 more key combos... I hate putting these things in Preferences, because it's not a preference but an additional action.

It could go in Go to Action (cmd-shift-D), but then it would be so obscure that there's hardly any point implementing it.
