### ISSUE TITLE
double project bar/split

### ISSUE THREAD

**Issue by stephenplatz** [fileability/chocolat-public#1759]
I have no idea how to reproduce, but restarting the app doesn't remove the problem. I'm on Yosemite and using version 3.1.7
![chocolat-grab](https://cloud.githubusercontent.com/assets/519156/12649553/e9aa4680-c593-11e5-9f93-16e2068ec406.jpg)

**Comment by locks** [comment]
Are you talking about the panel to the right? That's the symbol list, cmd-shift-i or View > Symbol List.

**Comment by stephenplatz** [comment]
Apparently yes! Thanks for your reply!
