### ISSUE TITLE
Add advanced prefs for text editor margins

### ISSUE THREAD

**Issue by fileability** [fileability/chocolat-public#31]
Add prefs to the advanced section top/left/right/bottom margins. These margins should play nicely with WriteRoom-like margins.

**Comment by locks** [comment]
This is [somewhat?] in Chocolat at least since `1.3.4`.
![screenshot 2015-06-26 03 19 35](https://cloud.githubusercontent.com/assets/32344/8369484/3e0ec0b6-1bb2-11e5-8691-5ccb852df62d.png)
