### ISSUE TITLE
Handle to resize sidebar is off-centre

### ISSUE THREAD

**Issue by cormacrelf** [fileability/chocolat-public#488]
I can get the cursor to about [here](http://cl.ly/ACub) before the standard resizing cursor comes up. It should activate 3 or 4 pixels either side of the line, but activates ~8 px to the left and 0px on the right side.

Sometimes, it doesn't even come up at all, but I can still resize the sidebar.

**Comment by fileability** [comment]
Time travelling dupe of issue number something-or-other that has a better discussion.
