### ISSUE TITLE
Embed a few additional popular monospaced fonts.

### ISSUE THREAD

**Issue by amcgregor** [fileability/chocolat-public#489]
I can highly recommend [embedding](http://stackoverflow.com/questions/2444717/embed-font-in-a-mac-bundle) a few additional fonts, license permitting, within the app bundle.  These are common developer choices: (with links to tasks in one of my own projects that contains licensing information and appropriate links to the font proper)

- [ProFontWindows](https://github.com/amcgregor/Syntax/issues/24)
- [NotCourierSans](https://github.com/amcgregor/Syntax/issues/23)
- [CPMono_v07](https://github.com/amcgregor/Syntax/issues/21)
- [BPmono](https://github.com/amcgregor/Syntax/issues/20)
- [Bitstream Vera Sans Mono](https://github.com/amcgregor/Syntax/issues/19)
- [Anonymous Pro](https://github.com/amcgregor/Syntax/issues/18)

I've already done the research as to embedded use licensing.  :)

**Comment by fileability** [comment]
Moved to wiki
