### ISSUE TITLE
Show whitespace invisibles when mixed.

### ISSUE THREAD

**Issue by amcgregor** [fileability/chocolat-public#523]
If leading whitespace on a line contains both spaces and tabs (which is almost _never_ a good thing), and show invisibles is enabled, then these spaces and tabs should show invisibles symbols.  This is particularly important for Python where mixing them is actually a syntax error.

**Comment by fileability** [comment]
Although this would be a nice feature, it kinda violates YOPFWYU as invisibles are relatively expensive.
