### ISSUE TITLE
Detecting file-changes correctly

### ISSUE THREAD

**Issue by ramitos** [fileability/chocolat-public#584]
I was following a compass/sass tutorial using the 'compass watch', when i tought: split view with the .sass and the generated .css would be great.

But actually that isn't that great, because if I save the .sass file, the .css view don' t refresh. Every time i save the .sass, the 'compass watch' detects the changes and saves a new version of the .css.

So, every time I save the .sass, the .css should refresh.

Here is an exemple:

![](http://f.cl.ly/items/2A1p3I172L210O0M1U39/file-changes1.png)

The .css should be like the next image, because of the @import in the line 6

![](http://f.cl.ly/items/3j2L0L2a1R1G2T1Q2V2b/file-changes2.png)

*PS: Sorry my 'not perfect' english. I'm not an native english speaker :)*

**Comment by fileability** [comment]
Have had no problems with this recently so closing.
