### ISSUE TITLE
Tab in Find bar goes to 'Find previous'

### ISSUE THREAD

**Issue by phortuin** [fileability/chocolat-public#786]
Pressing Tab in the 'Find' field puts the focus on the 'Find previous' button right next to it; pressing Tab again jumps to the 'Replace' field. I expect the focus to jump to 'Replace' after pressing Tab once, also because there is no visual indication of the 'Find previous' button having focus I suspect this is a bug.

**Comment by locks** [comment]
Previous/Next buttons now have a focus indicator.
